---
# Docs: https://docs.couchbase.com/server/current/cli/cbcli/couchbase-cli-server-add.html
- name: Add Nodes
  shell:
    cmd: |
      if /opt/couchbase/bin/couchbase-cli host-list \
        --cluster {{ hostvars[inventory_hostname].ansible_host }} \
        --username {{ couchbase_security.admin_user | default('Administrator') }} \
        --password '{{ admin_password | default('password') }}' | \
        grep -q '{{ item.ip }}'; then
          echo "The node already exists in the cluster"
      else
        /opt/couchbase/bin/couchbase-cli server-add \
          --cluster {{ inventory_hostname }} \
          --username {{ couchbase_security.admin_user | default('Administrator') }} \
          --password '{{ admin_password | default('password') }}' \
          --server-add-username {{ couchbase_security.admin_user | default('Administrator') }} \
          --server-add-password '{{ admin_password | default('password') }}' \
          --server-add {{ item.ip }} \
          --services '{{
            item.services is defined |
            ternary(item.services, couchbase_cluster.default_services |
            default(['data','index','query'])) |
            join(',') }}'
        fi
  with_items: "{{ couchbase_nodes }}"
  register: add_note
  when: couchbase_master is defined and item.hostname != couchbase_master
  changed_when: "'The node already exists in the cluster' not in add_note.stdout"
  tags:
    - couchbase_configure
    - couchbase_add_nodes
