---
# Docs: https://docs.couchbase.com/server/current/cli/cbcli/couchbase-cli-node-init.html
- name: Initialize the Node
  shell:
    cmd: |
      if /opt/couchbase/bin/couchbase-cli host-list \
        --cluster {{ hostvars[inventory_hostname].ansible_host }} \
        --username {{ couchbase_security.admin_user | default('Administrator') }} \
        --password '{{ admin_password | default('password') }}' | \
        grep -q '{{ hostvars[inventory_hostname].ansible_host }}'; then
          echo "The node already exists in the cluster"
      else
        /opt/couchbase/bin/couchbase-cli node-init \
          --cluster {{ hostvars[inventory_hostname].ansible_host }} \
          --username {{ couchbase_security.admin_user | default('Administrator') }} \
          --password '{{ admin_password | default('password') }}' \
          --node-init-hostname '{{ hostvars[inventory_hostname].ansible_host }}' \
          --node-init-data-path '{{ couchbase_paths.data }}' \
          --node-init-index-path '{{ couchbase_paths.index }}' \
          --node-init-analytics-path '{{ couchbase_paths.analytics }}' \
          --node-init-eventing-path '{{ couchbase_paths.eventing }}'
      fi
  with_items: "{{ couchbase_nodes }}"
  register: initialize_node
  changed_when: "'The node already exists in the cluster' not in initialize_node.stdout"
  when: couchbase_master is defined
