---
# Docs: https://docs.couchbase.com/server/current/cli/cbcli/couchbase-cli-setting-notification.html
- name: Set the Couchbase Notifications
  shell:
    cmd: |
      /opt/couchbase/bin/couchbase-cli setting-notification \
        --cluster {{ hostvars[inventory_hostname].ansible_host }} \
        --username {{ couchbase_security.admin_user | default('Administrator') }} \
        --password '{{ admin_password | default('password') }}' \
        --enable-notifications {{ couchbase_cluster.notifications | default(true) | int }}
  when: couchbase_master is defined and couchbase_master == hostvars[inventory_hostname].ansible_host
  changed_when: false
  tags:
    - couchbase_configure
    - couchbase_notifications
