---
# Docs: https://docs.couchbase.com/server/current/cli/cbcli/couchbase-cli-setting-password-policy.html
- name: Set the Couchbase Password Policy
  shell:
    cmd: |
      /opt/couchbase/bin/couchbase-cli setting-password-policy \
        --cluster {{ hostvars[inventory_hostname].ansible_host }} \
        --username {{ couchbase_security.admin_user | default('Administrator') }} \
        --password '{{ couchbase_security.admin_password | default('password') }}' \
        --min-length {{ couchbase_password_policy.min_length | default(6) | int }} \
        --uppercase {{ couchbase_password_policy.uppercase | default(false) | int }} \
        --lowercase {{ couchbase_password_policy.lowercase | default(false) | int }} \
        --digit {{ couchbase_password_policy.digit | default(false) | int }} \
        --special-char {{ couchbase_password_policy.special_char | default(false) | int }} \
        --set
  when: couchbase_master is defined and couchbase_master == hostvars[inventory_hostname].ansible_host
  changed_when: false
  tags:
    - couchbase_configure
    - couchbase_password_policy
