---
- name: "Wait for Couchbase on all hosts in cluster to come up"
  uri:
    url: "http://{{ hostvars[inventory_hostname].ansible_host }}:8091/pools"
    method: GET
    user: "{{ couchbase_security.admin_user }}"
    password: "{{ admin_password }}"
  register: _result
  until: _result.status == 200
  retries: 60
  delay: 1
  with_items: "{{ couchbase_nodes }}"
  when: couchbase_master is defined and couchbase_master == hostvars[inventory_hostname].ansible_host
