---
- name: Check if the disable-thp script has been installed already
  stat:
    path: /etc/init.d/disable-thp
  register: disable_thp
  tags:
    - couchbase_os
    - couchbase_thp

- name: Install Disable THP Script
  template:
    src: etc/init.d/disable-thp.j2
    dest: /etc/init.d/disable-thp
    mode: "755"
  when: not disable_thp.stat.exists
  tags:
    - couchbase_os
    - couchbase_thp

- name: Register the Disable THP Script as a Service
  service:
    name: disable-thp
    enabled: true
    state: started
  tags:
    - couchbase_os
    - couchbase_thp
